services:
  app:
    container_name: spec
    build:
      dockerfile: Dockerfile
      context: .
    command: bash -lc "cd /files && ./generate.sh"
    volumes:
      - .:/files
    environment:
      - STAGING_DOCS=${STAGING_DOCS:-false}
