openapi: 3.0.3

info:
  title: Formaloo API Documentation
  version: 3.0.0
  description:
    $ref: ./docs/v3.0/intro.md
  termsOfService: https://www.formaloo.com/terms
  contact:
    name: Support
    email: dev@formaloo.com
    url: https://help.formaloo.com/en/
  externalDocs:
    description: Find out more
    url: https://help.formaloo.com/en/

servers:
  - url: https://api.formaloo.me
    description: Production Server

components:
  securitySchemes:
    JWT Authentication:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "JWT"